# Generated by Django 2.2.5 on 2019-09-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'base_skill',
                'verbose_name_plural': 'base_skill',
                'db_table': 'base_skill',
            },
        ),
    ]
