####
POST http://localhost:8000/api/v1/auth/login/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "username": "admin",
  "password": "A1qwerty"
}

####
GET http://localhost:8000/api/v1/workers/
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json



####