# Generated by Django 2.2.5 on 2019-09-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(upload_to='companies/logos')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companyes',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='EmployerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_role_custom_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'employer_role',
                'verbose_name_plural': 'employer_roles',
                'db_table': 'employer_role',
            },
        ),
    ]
