# Generated by Django 2.2.5 on 2019-09-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20190914_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employercompany',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employercompany',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employerrole',
            name='position',
        ),
        migrations.AddField(
            model_name='employerrole',
            name='company_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerrole',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerrole',
            name='company_logo',
            field=models.ImageField(default='', upload_to='companies/logos'),
        ),
        migrations.AddField(
            model_name='employerrole',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='EmployerCompany',
        ),
    ]
