# Generated by Django 2.2.5 on 2019-09-14 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.ImageField(default=0, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_role_custom_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'worker_role',
                'verbose_name_plural': 'worker_role',
                'db_table': 'worker_role',
            },
        ),
        migrations.CreateModel(
            name='WorkerSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_skills_base_skill', to='skills.BaseSkill')),
                ('worker_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_skills_worker_role', to='workers.WorkerRole')),
            ],
            options={
                'verbose_name': 'worker_skill',
                'verbose_name_plural': 'worker_skill',
                'db_table': 'worker_skill',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('worker_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_worker_role', to='workers.WorkerRole')),
            ],
            options={
                'verbose_name': 'custom_user_experience',
                'verbose_name_plural': 'custom_user_experience',
                'db_table': 'custom_user_experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('worker_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations_worker_role', to='workers.WorkerRole')),
            ],
            options={
                'verbose_name': 'custom_user_education',
                'verbose_name_plural': 'custom_user_education',
                'db_table': 'custom_user_education',
            },
        ),
    ]
