# Generated by Django 2.2.5 on 2019-09-14 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_auto_20190914_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_role_custom_user', to=settings.AUTH_USER_MODEL, to_field='id'),
        ),
    ]
